# The name of this app. Must be unique within a project.
name: feathers-js-app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Node.js documentation
# (https://docs.platform.sh/languages/nodejs.html#supported-versions)
# to find the supported versions for the 'nodejs' type.
type: 'nodejs:16'
build:
  flavor: none

# The size of the persistent disk of the application (in MB).
disk: 512

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
    mongodatabase: 'dbmongo:mongodb'

hooks:
  build: |
    set -e
    npm install

web:
  commands: 
    start: "npm start"
  locations:
    "/":
      root: "public"
      headers:
        X-Frame-Options: SAMEORIGIN
      expires: 300
      allow: false
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg|map)$:
          allow: true
        ^/robots\.txt$:
          allow: false